name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg?color_dots=#0d1b2a,#1b4965,#247ba0,#3fa7d6,#7dd3fc
            github-contribution-grid-snake-dark.svg?color_dots=#0d1b2a,#1b4965,#247ba0,#3fa7d6,#7dd3fc

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: .
